# fly.toml app configuration file generated for wildleague-web on 2023-11-07T22:07:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wildleague-web"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
